let person = {
    nome: 'Jean Carlos Pereira',
    idade: '43',
    pais: 'Brasil.',
    paisDeMorada: 'Portugal',
    Distrito: 'Viana do Castelo.',
    ramoProfissional: 'desenhista, técnico em informática',
    conteudoCursoTecnico: 'web designer, redes, tabelas dinâmicas, manutenção de micros, sistemas em java, e trabalhos em CorelDraw.',
    estadoCivil: 'casado',
    curso: 'QA',
    cidade: 'Belém',
    EstadoNorte: 'Pará',
    esposa: 'Silvia Cristina Avelar Pereira',
    hobbis: 'desenhar, assistir a filmes, tocar violão.',
    estudos: 'Engenharia Mecânica',
    ferramentas: 'Cypress, Selenium, JIRA',
    empresa: 'Whirlpool Latin America',
    etiquetaProduto: 'selo de qualidade.',
    função1: 'Operador Pleno',
    função2: 'Operador Qualificado',
    tipoDeFuncao: 'Sketch',
    cidadeSulBrasil:'Joinville',
    EstadoSulBrasil:'Santa Catarina',
    linguagens: 'HTML, CSS, JavaScript.',
    TestesAPI: 'Insomnia, Swagger, Postman, BDD.',
    resumo: 'Sou uma pessoa Disposta e Interessado em novos desafios e que sempre busca o lado positivo. Faço parte de um Projeto Piloto de testes, onde nós alunos da Tech Fixe, fazemos simulações de testes de um profissional de QA. Assim, sempre estamos atualizados nos conhecimentos adquiridos nas Formações.',
}
console.log('Chamo-me ' + person.nome, 'tenho ' + person.idade, 'anos. Sou ' + person.estadoCivil, 'com ' + person.esposa, 'e sou natural do ' + person.pais,'Moro em ' + person.paisDeMorada, 'há 4 anos, Residente atualmente em '+ person.Distrito, 'Meus Hobbys são: ' + person.hobbis, 'Cursei ' + person.estudos, 'durante 3 anos (Curso Trancado por Motivo de Imigração), e já atuei em vários seguimentos no ramo profissional, tais como: ' + person.ramoProfissional, 'em órgão público na cidade de ' + person.cidade, ' do ' + person.EstadoNorte, ' no ' + person.pais, 'durante 3 anos, com inicio em 2010 e término em 2013, onde consegui colocar em prática vários conteúdos aprendidos no curso técnico, desde ' + person.conteudoCursoTecnico, 'Já trabalhei em área de Produção Em ' + person.EstadoSulBrasil, 'no Sul do Brasil, especificamente em ' + person.cidadeSulBrasil, ' na ' + person.empresa, 'como ' + person.função1, 'e ' + person.função2, ' onde fui convidado para integrar uma equipa de engenharia, para desenvolver e relatar situações por meio de ' + person.tipoDeFuncao, 'num projeto de WCM, (World Class Manufacturing), onde elevava o nível dos produtos fabricados, e estes recebiam um ' + person.etiquetaProduto, 'Hoje sou estudante de ' + person.curso, 'onde aprendi sobre o uso de ferramentas tipo: ' + person.ferramentas, 'e framework para teste de API como: ' + person.TestesAPI, 'Aprendi sobre as linguagens de programação: ' + person.linguagens, ' RESUMO: ' + person.resumo,)
